# Generated by Django 3.1.7 on 2021-03-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210322_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='text-product'),
            preserve_default=False,
        ),
    ]
