# Generated by Django 3.1.7 on 2021-03-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dscounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
