# Generated by Django 3.1.7 on 2021-03-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_dscounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='dscounted_price',
            new_name='discounted_price',
        ),
    ]
