# Generated by Django 3.1.7 on 2021-04-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210409_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_choice',
            field=models.CharField(blank=True, choices=[('N', 'NEW'), ('B', 'BESTSELLER'), ('P', '')], max_length=1, null=True),
        ),
    ]
