# Generated by Django 3.1.7 on 2021-03-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210329_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
